delicierr/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('orders.urls')),
    path('products/', include('products.urls')),
    # TODO remover depois
    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.OrderListViewHome.as_view(),
         name="home"
         ),
    path('orders/<int:pk>/', views.OrderDetailView.as_view(),
         name="show_order"
         ),
    path('orders/neworder/', views.ShowClientsToNewOrderView.as_view(),
         name="clients-new-order"
         ),
    path('orders/<int:pk>',
         views.create_order,
         name='order_create'
         ),

]

products/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path('addorderitem/', views.AddOrderItemView.as_view(),
         name="add_order_item"
         ),
    path('removeorderitem/', views.RemoveOrderItemView.as_view(),
         name="remove_order_item"
         ),
    path('product/<int:pk>', views.ProductDetailView.as_view(),
         name="detail"
         ),
]

products/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.


class Category(models.Model):
    name = models.CharField('Title', max_length=50)

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')

    def __str__(self):
        return self.name


class Product(models.Model):
    active = models.BooleanField(_('Active'))
    name = models.CharField(_('Title'), max_length=150)
    description = models.CharField(
        _("Long Description"),
        max_length=300,
        blank=True
    )
    slug = models.SlugField(unique=True)
    price = models.FloatField()
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'{self.name}'


class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    name = models.CharField(_("name"), max_length=150)
    price = models.FloatField()
    price_additional = models.FloatField(default=0.0, blank=True)
    price_discount = models.FloatField(default=0.0, blank=True)

    class Meta:
        verbose_name = _("variation")
        verbose_name_plural = _("variations")

    def __str__(self):
        return f'{self.product.name} {self.name}' or self.product.name

products/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import DetailView, View

from .models import Product, Variation

# Create your views here.


class AddOrderItemView(View):
    def get(self, *args, **kwargs):
        http_referer = self.request.META.get(
            'HTTP_REFERER',
            reverse('orders:home')
        )
        variation_id = self.request.GET.get('vid')

        variation = get_object_or_404(Variation, id=variation_id)
        variation_name = variation.name
        product = variation.product
        product_sabor = self.request.GET.get('orderitem_sabor')
        product_id = product.pk
        product_name = product.name
        product_price = variation.price
        product_amount = 1

        if not self.request.session.get('carrinho'):
            self.request.session['carrinho'] = {}
            self.request.session.save()

        carrinho = self.request.session['carrinho']

        if variation_id in carrinho:
            quantidade_carrinho = carrinho[variation_id]['product_amount']
            quantidade_carrinho += 1
            carrinho[variation_id]['product_amount'] = quantidade_carrinho
        else:
            carrinho[variation_id] = {
                'product_id': product_id,
                'product_name': product_name,
                'variation_id': variation_id,
                'variation_name': variation_name,
                'product_price': product_price,
                'product_amount': product_amount,
                'product_sabor': product_sabor,
            }
        self.request.session.save()

        messages.success(
            self.request,
            f'Produto {product_name} {variation_name} adicionado ao seu '
            f'carrinho {carrinho[variation_id]["product_amount"]}x.'
        )
        return redirect(http_referer)


class RemoveOrderItemView(View):
    pass


class ProductDetailView(DetailView):
    model = Product
    context_object_name = 'produto'
    template_name = 'products/pages/product_detail.html'

products/templates/products/pages/product_detail.html
{% extends 'global/base.html' %}

{% load static %}
{% block title %} New Order | {% endblock title %}




{% block content %}

    
    <div class="container text-white">
        <div class="row justify-content-center">
            <div class="col-8">
                <h1 class="text-white">Select a {{produto.name}} Variation</h1>
                
                {% include 'global/partials/_messages.html' %}


                <form action=" {% url 'products:add_order_item' %}" id="form_add_to_cart">
                    <div class="form-group">
                        <select id="select-variations" name="vid" class="form-control">
                            
                            {% for variation in produto.variation_set.all %}
                                <option value="{{ variation.pk }}">{{variation.name}}</option>
                            {% endfor %}
                                
                        </select>
                    </div>
                    <div class="form-group mt-2">
                        <label for="orderitem_sabor">Sabor</label>
                        <input type="text" name="orderitem_sabor" id="orderitem_sabor">
                    </div>
                    <button type="submit" class="btn btn-primary mt-3">Save Order</button>
                </form>
            </div>
        </div>
        
    </div>
{% endblock content %}