delicierr/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('orders.urls')),
    path('products/', include('products.urls')),
    # TODO remover depois
    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.OrderListViewHome.as_view(),
         name="home"
         ),
    path('orders/<int:pk>/', views.OrderDetailView.as_view(),
         name="show_order"
         ),
    path('orders/neworder/', views.ShowClientsToNewOrderView.as_view(),
         name="clients-new-order"
         ),
    path('orders/<int:pk>',
         views.create_order,
         name='order_create'
         ),

]

products/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path('addorderitem/', views.AddOrderItemView.as_view(),
         name="add_order_item"
         ),
    path('removeorderitem/', views.RemoveOrderItemView.as_view(),
         name="remove_order_item"
         ),
    path('product/<int:pk>', views.ProductDetailView.as_view(),
         name="detail"
         ),
]

orders/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from clients.models import Client

# Create your models here.


class Order (models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    total = models.FloatField(default=0.0)
    delivery_date = models.DateTimeField(
        'Delivery Date', auto_now=False, auto_now_add=False)
    for_delivery = models.BooleanField()

    delivery_method = models.CharField(
        choices=(
            ('P', 'Própria'),
            ('T', 'App Terceirizado')
        ),
        max_length=1,
        blank=True
    )
    delivery_address = models.CharField(blank=True, max_length=300)
    comments = models.TextField(max_length=500, blank=True)
    status_order = models.CharField(
        choices=(
            ('CR', 'CREATED'),
            ('CL', 'CANCELED'),
            ('CF', 'CONFIRMED'),
            ('FN', 'FINISHED'),
        ),
        max_length=2,
        default='CR',
    )
    payment_form = models.CharField(
        _("Payment Form"),
        max_length=2,
        blank=True,
        choices=(
            ('CS', _('CASH')),
            ('CC', _('CREDIT CARD')),
            ('DC', _('DEBIT CARD')),
            ('PX', _('PIX')),
        ),
        default='PX',
    )
    status_payment = models.CharField(
        choices=(
            ('NP', 'NOT PAID'),
            ('PG', 'PAID'),
            ('PE', 'PAID ENTRY'),
        ),
        max_length=2,
        blank=True,
        default='NP',
    )

    class Meta:
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'

    def __str__(self):
        return str(f'{self.pk}-{self.delivery_date.year}')


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.CharField(max_length=150)
    product_id = models.PositiveIntegerField()
    variation = models.CharField(max_length=150)
    variation_id = models.PositiveIntegerField()
    sabor = models.CharField(max_length=50, blank=True, default=None)
    price = models.FloatField()
    price_additional = models.FloatField(blank=True, default=0.0)
    price_discount = models.FloatField(blank=True, default=0.0)
    amount = models.PositiveIntegerField()

    class Meta:
        verbose_name = "Order Item"
        verbose_name_plural = "Order Itens"

orders/forms/new_order_form.py
from collections import defaultdict

from django import forms
from django.utils.translation import gettext_lazy as _

from orders.models import Order


class NewOrderForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._my_errors = defaultdict(list)

    class Meta:
        model = Order
        fields = [
            'client',
            'delivery_date',
            'for_delivery',
            'delivery_method',
            'delivery_address',
            'payment_form',
            'status_payment',
        ]
        widgets = {
            # 'client': forms.Select(
            #     attrs={
            #         '': 'disabled',
            #     }
            # ),

            'delivery_method': forms.Select(
                choices=(
                    ('P', 'Própria'),
                    ('T', 'App Terceirizado'),
                ),
                attrs={
                    'class': 'form-control'
                }
            ),
            'payment_form': forms.Select(
                choices=(
                    ('CS', _('CASH')),
                    ('CC', _('CREDIT CARD')),
                    ('DC', _('DEBIT CARD')),
                    ('PX', _('PIX')),
                ),
                attrs={
                    'class': 'form-control'
                }
            ),
        }

orders/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView, View

from clients.models import Client
from products.models import Product

from .models import Order

# Create your views here.


class OrderListViewBase(ListView):
    model = Order
    context_object_name = 'orders'
    ordering = ['delivery_date']
    template_name = 'orders/pages/home.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.exclude(
            status_order='CL',
        )
        return qs


class OrderListViewHome(OrderListViewBase):
    template_name = 'orders/pages/home.html'


class OrderDetailView(DetailView):
    model = Order
    context_object_name = 'order'
    template_name = 'orders/pages/order_detail.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.exclude(
            status_order='CL',
        )
        return qs


class ShowClientsToNewOrderView(View):
    def render_order(self):
        clients = Client.objects.all()

        return render(
            self.request,
            'orders/pages/clients.html',
            context={
                'clients': clients,
            }
        )

    def get(self, request, id=None):
        return self.render_order()


def create_order(request, pk):
    client = Client.objects.get(id=pk)
    produtos = Product.objects.all()
    carrinho = request.session.get('carrinho', {})
    # TODO criar template para mostrar produtos e adicionar ao carrinho
    context = {
        'cliente': client,
        'produtos': produtos,
        'carrinho': carrinho
    }
    return render(request, 'orders/pages/new_order_itens.html', context)

orders/templates/orders/partials/_clients_list.html
<div class="card">
    <div class="card-body">
        <table class="table">
            <thead>
                <th scope="col">#</th>
                <th scope="col">Client Name</th>
                <th scope="col">Cell Number</th>
                <th scope="col">Order</th>
            </thead>
            <tbody>
                
                {% for client in clients %}    
                    <tr>
                        <th scope="row">{{ client.pk }}</th>
                        <td>{{ client.name }}</td>
                        <td>{{ client.celphone }}</td>
                        <td>
                            <a href=" {% url 'orders:order_create' client.id %}" 
                            class="btn btn-success">
                                <i class="fa-sharp fa-solid fa-cart-plus text-white"></i>

                            </a>
                        </td>
                    </tr>
                {% endfor %}  
            </tbody>
        </table>
    </div>
</div>

orders/templates/orders/partials/_list_products_new_order.html
<h2 class="text-center  my-4 text-white">Add Order For <strong>{{cliente.name}}</strong> </h2></div>

<div class="card">
    <div class="card-body">
        {{request.client.name}}
        Custumer : {{cliente.name}}
        
        <div class="row">
            {% for produto in produtos %}
                <div class="col">
                    <div class="card" style="width: 24rem">
                        <div class="card-body text-center ">
                            <h4 class="card-title fw-bold">{{ produto.name }}</h4>
                            
                            <a href="{% url 'products:detail' produto.pk %}" class="btn btn-primary">Detalhar</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <!--
            TODO mostra o carrinho sendo montado
        
        -->
        <div class="row text-danger">
            <div class="col">
                algo aqui
                {% if request.session.carrinho %}
                    
                    <ul>
                        <li>daqui</li>
                        {% for item in carrinho.values %}
                            
                            <li>{{item.product_name}}</li>  
                        {% endfor %}
                    </ul>
                
                
                {% endif %}
            </div>
        </div>
    </div>
</div>

orders/templates/orders/partials/_order.html
<!-- Start order content -->
<div class="col pb-3">
    <div class="card h-100 w-100  text-white bg-white rounded-5 m-2">
        <div class="card-body text-dark">
            <p class="position-relative">
                <span
                    {% if order.status_payment == 'PG' %}
                    
                        class=" position-absolute top-50 start-50 badge translate-middle text-bg-success fs-5"
                    {% elif order.status_payment == 'NP'%}
                        class=" position-absolute top-50 start-50 badge translate-middle text-bg-danger fs-5"
                    {% else %}
                        class=" position-absolute top-50 start-50 badge translate-middle text-bg-warning fs-5"
                    {% endif %}
                >
                    {{ order.get_status_payment_display }}
                </span>
            </p>
            <h4 class="text-center card-title">
                <a href="#" class="text-decoration-none fw-semibold">
                    {{ order }}
                </a>
                {% comment %} icon to inform if order is confirmed {% endcomment %}
                {% if order.status_order == 'CF' %}
                    <i class="fa-solid fa-thumbs-up text-success"></i>
                {% endif %}
            </h4>
            <hr>
            <p class="card-text">
                <b>Client name: </b>
                    <a href="./client_detail.html" data-bs-toggle="tooltip"
                        data-bs-title="Click for client details">
                        {{ order.client.name }}
                    </a>
            </p>
            <p class="card-text">
                <b>Delivery date</b>: {{ order.delivery_date|date:"d/m/Y" }}
            </p>
            <p class="card-text">
                <b>Delivery time</b>: {{ order.delivery_date|date:"H:i" }}
            </p>
            <p class="card-text">
                <b>For delivery:</b> 
                
                {% if order.for_delivery %}
                    Yes
                {% else %}
                    No
                {% endif %}
                    
            </p>
                <!--TODO Acho isto desnecessário aqui só polui o template, confirmar com marcella-->
                {% comment %} {% if order.for_delivery %}
                    <p class="card-text">
                        <b>Delivery method:</b> {{order.get_delivery_method_display}}
                    </p>

                    <p class="card-text">
                        <b>Delivery address:</b> {{order.delivery_address}}
                    </p>
                                    
                {% endif %} {% endcomment %}
            
            
            <p class="card-text text-center"><b>Order Resume</b></p>
            <hr>
            <ul class="list-group list-group-flush ms-3 mb-3">
                
                
                {% for item in order.orderitem_set.all %}
                    <li>{{ item.amount }} {{ item.product }} {{ item.variation }}</li>
                {% endfor %}
                
            </ul>
            <div class="row">
                <a href="{% url 'orders:show_order' order.id %}"
                class="btn btn-primary btn-block fw-bold">
                    <i class="fa-solid fa-eye me-1"></i>
                    More details...
                </a>
            </div>
        </div>
    </div>
</div>
<!-- End order content -->

orders/templates/orders/partials/clients_list.html
<div class="card">
    <div class="card-body">
        <table class="table">
            <thead>
                <th scope="col">#</th>
                <th scope="col">Client Name</th>
                <th scope="col">Cell Number</th>
                <th scope="col">Order</th>
            </thead>
            <tbody>
                
                {% for client in clients %}    
                    <tr>
                        <th scope="row">{{ client.pk }}</th>
                        <td>{{ client.name }}</td>
                        <td>{{ client.celphone }}</td>
                        <td>
                            <a href=" {% url 'orders:order_create' client.id %}" 
                            class="btn btn-success">
                                <i class="fa-sharp fa-solid fa-cart-plus text-white"></i>

                            </a>
                        </td>
                    </tr>
                {% endfor %}  
            </tbody>
        </table>
    </div>
</div>

orders/templates/orders/partials/order.html
<!-- Start order content -->
<div class="col pb-3">
    <div class="card h-100 w-100  text-white bg-white rounded-5 m-2">
        <div class="card-body text-dark">
            <p class="position-relative">
                <span
                    {% if order.status_payment == 'PG' %}
                    
                        class=" position-absolute top-50 start-50 badge translate-middle text-bg-success fs-5"
                    {% elif order.status_payment == 'NP'%}
                        class=" position-absolute top-50 start-50 badge translate-middle text-bg-danger fs-5"
                    {% else %}
                        class=" position-absolute top-50 start-50 badge translate-middle text-bg-warning fs-5"
                    {% endif %}
                >
                    {{ order.get_status_payment_display }}
                </span>
            </p>
            <h4 class="text-center card-title">
                <a href="#" class="text-decoration-none fw-semibold">
                    {{ order }}
                </a>
                {% comment %} icon to inform if order is confirmed {% endcomment %}
                {% if order.status_order == 'CF' %}
                    <i class="fa-solid fa-thumbs-up text-success"></i>
                {% endif %}
            </h4>
            <hr>
            <p class="card-text">
                <b>Client name: </b>
                    <a href="./client_detail.html" data-bs-toggle="tooltip"
                        data-bs-title="Click for client details">
                        {{ order.client.name }}
                    </a>
            </p>
            <p class="card-text">
                <b>Delivery date</b>: {{ order.delivery_date|date:"d/m/Y" }}
            </p>
            <p class="card-text">
                <b>Delivery time</b>: {{ order.delivery_date|date:"H:i" }}
            </p>
            <p class="card-text">
                <b>For delivery:</b> 
                
                {% if order.for_delivery %}
                    Yes
                {% else %}
                    No
                {% endif %}
                    
            </p>
                <!--TODO Acho isto desnecessário aqui só polui o template, confirmar com marcella-->
                {% comment %} {% if order.for_delivery %}
                    <p class="card-text">
                        <b>Delivery method:</b> {{order.get_delivery_method_display}}
                    </p>

                    <p class="card-text">
                        <b>Delivery address:</b> {{order.delivery_address}}
                    </p>
                                    
                {% endif %} {% endcomment %}
            
            
            <p class="card-text text-center"><b>Order Resume</b></p>
            <hr>
            <ul class="list-group list-group-flush ms-3 mb-3">
                
                
                {% for item in order.orderitem_set.all %}
                    <li>{{ item.amount }} {{ item.product }} {{ item.variation }}</li>
                {% endfor %}
                
            </ul>
            <div class="row">
                <a href="{% url 'orders:show_order' order.id %}"
                class="btn btn-primary btn-block fw-bold">
                    <i class="fa-solid fa-eye me-1"></i>
                    More details...
                </a>
            </div>
        </div>
    </div>
</div>
<!-- End order content -->